version: '2'
networks:
  default:
    ipam:
      config:
       - subnet: 172.18.0.0/24
         ip_range: 172.18.0.0/24
         gateway: 172.18.0.1 

services:
  #set of abstract utility servers
  vpn:
    image: clusterkit/vpn
    networks:
      default:
        ipv4_address: 172.18.0.253
    privileged: true
    ports:
     - "1194:1194"
    environment:
     - DEBUG=1


  nuget:
    #image: sunside/simple-nuget-server
    image: clusterkit/nuget
    ports:
     - "81:80"
    environment:
     - NUGET_API_KEY=ClusterKit
    networks:
      default:
        ipv4_address: 172.18.0.2 

  configDb:
    image: clusterkit/postgres
    networks:
      default:
        ipv4_address: 172.18.0.3
  redis:
    image: clusterkit/redis
    privileged: true
    networks:
      default:
        ipv4_address: 172.18.0.4
     
  entry:
    image: clusterkit/entry
    links:
     - "seed"
     - "publisher1"
     - "publisher2"
    ports:
     - "80:80"
    networks:
      default:
        ipv4_address: 172.18.0.5     

  #Cluster servers
  seed: #seeds should be limited and with fixed addresses preknown to other cluster nodes
    image: clusterkit/seed
    environment:
     - NETWORK_NAME=seed
     - SELF_JOIN=true
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.6               

  publisher1: 
    image: clusterkit/publisher
    environment:
     - NETWORK_NAME=publisher1
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.7               


  publisher2: 
    image: clusterkit/publisher
    environment:
     - NETWORK_NAME=publisher2
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.8             

  manager:
    image: clusterkit/manager
#    environment:
#     - MONO_LOG_LEVEL=info
    links:
     - "seed"
     - "configDb"
     - "nuget"
     - "entry"
    logging:
        driver: json-file

  monitoringUI:
    image: clusterkit/monitoring-ui
    ports:
     - "82:8080"
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.9 
  
  elk:
    image: clusterkit/elk
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.12
  
  seeder:
    image: clusterkit/seeder
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.13


  worker:
    image: clusterkit/worker
    links:
     - "seed"
     - "manager"
     - "nuget"
     - "configDb"
     - "entry"
    logging:
        driver: json-file
