image: Visual Studio 2017
environment:
  version: '0.0.{build}-{branch}'
install:
  - choco install fake -pre
build_script:
  - fake run build.fsx
test_script:
  - fake run -t "Tests" build.fsx
artifacts:
  - path: packageOut
