dotnet build /t:Publish -f netcoreapp1.1 .\KlusterKite.NodeManager\KlusterKite.NodeManager.FallbackPackageFixer\KlusterKite.NodeManager.FallbackPackageFixer.csproj

del Docker\KlusterKiteManager\fallBackConfiguration.json
copy Docker\KlusterKiteManager\fallBackConfiguration.orig Docker\KlusterKiteManager\fallBackConfiguration.json
dotnet .\KlusterKite.NodeManager\KlusterKite.NodeManager.FallbackPackageFixer\bin\Debug\netcoreapp1.1\publish\KlusterKite.NodeManager.FallbackPackageFixer.dll Docker\KlusterKiteManager\fallBackConfiguration.json packageOut packageThirdPartyDir 

del Docker\KlusterKitePublisher\fallBackConfiguration.json
copy Docker\KlusterKitePublisher\fallBackConfiguration.orig Docker\KlusterKitePublisher\fallBackConfiguration.json
dotnet .\KlusterKite.NodeManager\KlusterKite.NodeManager.FallbackPackageFixer\bin\Debug\netcoreapp1.1\publish\KlusterKite.NodeManager.FallbackPackageFixer.dll Docker\KlusterKitePublisher\fallBackConfiguration.json packageOut packageThirdPartyDir 