dotnet build /t:Publish -f netcoreapp1.1 .\ClusterKit.NodeManager\ClusterKit.NodeManager.FallbackPackageFixer\ClusterKit.NodeManager.FallbackPackageFixer.csproj

del Docker\ClusterKitManager\fallBackConfiguration.json
copy Docker\ClusterKitManager\fallBackConfiguration.orig Docker\ClusterKitManager\fallBackConfiguration.json
dotnet .\ClusterKit.NodeManager\ClusterKit.NodeManager.FallbackPackageFixer\bin\Debug\netcoreapp1.1\publish\ClusterKit.NodeManager.FallbackPackageFixer.dll Docker\ClusterKitManager\fallBackConfiguration.json packageOut packageThirdPartyDir 

del Docker\ClusterKitPublisher\fallBackConfiguration.json
copy Docker\ClusterKitPublisher\fallBackConfiguration.orig Docker\ClusterKitPublisher\fallBackConfiguration.json
dotnet .\ClusterKit.NodeManager\ClusterKit.NodeManager.FallbackPackageFixer\bin\Debug\netcoreapp1.1\publish\ClusterKit.NodeManager.FallbackPackageFixer.dll Docker\ClusterKitPublisher\fallBackConfiguration.json packageOut packageThirdPartyDir 