version: '2.1'
networks:
  default:
    ipam:
      config:
       - subnet: 172.18.0.0/24
         ip_range: 172.18.0.0/24
         gateway: 172.18.0.1 

services:
  #set of abstract utility servers
  vpn:
    image: klusterkite/vpn
    networks:
      default:
        ipv4_address: 172.18.0.253
    privileged: true
    ports:
     - "1194:1194"
    environment:
     - DEBUG=1


  nuget:
    #image: sunside/simple-nuget-server
    image: klusterkite/nuget
    ports:
     - "81:80"
    environment:
     - NUGET_API_KEY=KlusterKite
    networks:
      default:
        ipv4_address: 172.18.0.2 

  configDb:
    image: klusterkite/postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      default:
        ipv4_address: 172.18.0.3
  redis:
    image: klusterkite/redis
    privileged: true
    networks:
      default:
        ipv4_address: 172.18.0.4
     
  entry:
    image: klusterkite/entry
    depends_on:
      - publisher1
      - publisher2
    links:
     - "seed"
     - "publisher1"
     - "publisher2"
    ports:
     - "80:80"
    networks:
      default:
        ipv4_address: 172.18.0.5

  #Cluster servers
  seed: #seeds should be limited and with fixed addresses preknown to other cluster nodes
    image: klusterkite/seed
    environment:
     - NETWORK_NAME=seed
     - SELF_JOIN=true
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.6               

  publisher1:
    image: klusterkite/publisher
    environment:
     - NETWORK_NAME=publisher1
    depends_on:
      seeder:
        condition: service_completed_successfully
    volumes:
      - bootstrap:/fallback:ro
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.7


  publisher2:
    image: klusterkite/publisher
    environment:
     - NETWORK_NAME=publisher2
    depends_on:
      seeder:
        condition: service_completed_successfully
    volumes:
      - bootstrap:/fallback:ro
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.8

  monitoringUI:
    image: klusterkite/monitoring-ui
    depends_on:
      - entry
    ports:
     - "82:80"
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.9
  
  elasticsearch:
    image: klusterkite/elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.12

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.28
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.14
  
  seeder:
    image: klusterkite/seeder
    depends_on:
      - configDb
      - nuget
    volumes:
      - bootstrap:/fallback
    logging:
        driver: json-file
    networks:
      default:
        ipv4_address: 172.18.0.13


  manager:
    image: klusterkite/manager
    environment:
     - NETWORK_NAME=manager
    depends_on:
      seeder:
        condition: service_completed_successfully
    links:
     - "seed"
     - "configDb"
     - "nuget"
     - "entry"
     - "publisher1"
     - "publisher2"
    volumes:
      - bootstrap:/fallback:ro
    logging:
        driver: json-file

  worker:
    image: klusterkite/worker
    environment:
     - NETWORK_NAME=worker
    depends_on:
      seeder:
        condition: service_completed_successfully
    links:
     - "seed"
     - "manager"
     - "nuget"
     - "configDb"
     - "entry"
     - "publisher1"
     - "publisher2"
    volumes:
      - bootstrap:/fallback:ro
    logging:
        driver: json-file

volumes:
  bootstrap:
