version: '2'
services:
  seed:
    image: clusterkit/seed
    ports:
     - "80:80"
    environment:
     - NETWORK_NAME=seed
  nuget:
    image: sunside/simple-nuget-server
    ports:
     - "81:80"
    environment:
     - NUGET_API_KEY=ClusterKit
  configDb:
    image: postgres
    environment:
     - NETWORK_NAME=postgres
  manager1:
    image: clusterkit/demoworker
    links:
     - "seed"
     - "configDb"
    environment:
     - NETWORK_NAME=manager1
  manager2:
    image: clusterkit/demoworker    
    links:
     - "seed"
     - "configDb"
    environment:
     - NETWORK_NAME=manager2
  worker:
    image: clusterkit/worker    
    links:
     - "seed"
     - "configDb"
     - "manager1"
     - "manager2"
     - "nuget"    

