version: '2'
services:
  seed:
    image: clusterkit/seed
    ports:
     - "80:80"
    environment:
     - NETWORK_NAME=seed
  worker1:
    image: clusterkit/worker
    links:
     - "seed"
    environment:
     - NETWORK_NAME=worker1
  worker2:
    image: clusterkit/worker    
    links:
     - "seed"
    environment:
     - NETWORK_NAME=worker2

