version: '2'
services:
  #set of abstract utility servers
  nuget:
    #image: sunside/simple-nuget-server
    image: clusterkit/nuget
    ports:
     - "81:80"
    environment:
     - NUGET_API_KEY=ClusterKit
  configDb:
    image: clusterkit/postgres
    environment:
     - NETWORK_NAME=postgres
  monitoringUI:
    image: clusterkit/monitoring-ui
    ports:
     - "82:8080"


  #Cluster servers
  seed: #seeds should be limited and with fixed addresses preknown to other cluster nodes
    image: clusterkit/seed
    ports:
     - "80:80"
    environment:
     - NETWORK_NAME=seed
  manager:
    image: clusterkit/manager
    links:
     - "seed"
     - "configDb"    
  worker:
    image: clusterkit/worker    
    links:
     - "seed"
     - "manager"
     - "nuget"    

