declare -x OVPN_AUTH=""
declare -x OVPN_CIPHER=""
declare -x OVPN_CLIENT_TO_CLIENT
declare -x OVPN_CN="docker"
declare -x OVPN_COMP_LZO
declare -x OVPN_DEFROUTE="1"
declare -x OVPN_DEVICE="tun"
declare -x OVPN_DNS="1"
declare -x OVPN_ENV="/etc/openvpn/ovpn_env.sh"
declare -x OVPN_FRAGMENT
declare -x OVPN_MTU
declare -x OVPN_NAT="0"
declare -x OVPN_OTP_AUTH
declare -x OVPN_PORT="1194"
declare -x OVPN_PROTO="tcp"
declare -ax OVPN_PUSH='()'
declare -ax OVPN_ROUTES='([0]="192.168.254.0/24")'
declare -x OVPN_SERVER="192.168.255.0/24"
declare -x OVPN_SERVER_URL="tcp://docker"
declare -x OVPN_TLS_CIPHER=""
