var dir_6e363153df76ac47cc205ef2564193b6 =
[
    [ "KlusterKite.API.Tests.AssemblyInfo.cs", "net46_2_kluster_kite_8_a_p_i_8_tests_8_assembly_info_8cs.html", null ],
    [ "KlusterKite.API.Tests.Program.cs", "net46_2_kluster_kite_8_a_p_i_8_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_kluster_kite_8_a_p_i_2_kluster_kite_8_a_p_i_8_tests_2obj_2_debug_2net46_2_temporary_generated_f4554f616e0dd2714e8a6e24f9efe7322.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_kluster_kite_8_a_p_i_2_kluster_kite_8_a_p_i_8_tests_2obj_2_debug_2net46_2_temporary_generated_fe4e8cbd3e8c1720aaa5f66b1fd477759.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_kluster_kite_8_a_p_i_2_kluster_kite_8_a_p_i_8_tests_2obj_2_debug_2net46_2_temporary_generated_f721b7abf5c55d9d2e1d5606dd9fef7a2.html", null ]
];