var dir_7d1f10ff5a3edae919d1491910fa2d4f =
[
    [ "KlusterKite.Monitoring.Tests.AssemblyInfo.cs", "netcoreapp1_81_2_kluster_kite_8_monitoring_8_tests_8_assembly_info_8cs.html", null ],
    [ "KlusterKite.Monitoring.Tests.Program.cs", "netcoreapp1_81_2_kluster_kite_8_monitoring_8_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_kluster_kite_8_monitoring_2_kluster_kite_8_monitoring_8_tests_2obj_2_debug_2netcoreapp1_81_2_te2fc11a7c2ab327fb76c3c5e77caf128d.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_kluster_kite_8_monitoring_2_kluster_kite_8_monitoring_8_tests_2obj_2_debug_2netcoreapp1_81_2_tea2b862e44565bd6e4e69c1c100140104.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_kluster_kite_8_monitoring_2_kluster_kite_8_monitoring_8_tests_2obj_2_debug_2netcoreapp1_81_2_tef935337c8c73069bec6cf15c6660d71d.html", null ]
];