var dir_2cad7572fe95e3b255e4c3c791cab5e3 =
[
    [ "KlusterKite.API.Tests.AssemblyInfo.cs", "netcoreapp1_81_2_kluster_kite_8_a_p_i_8_tests_8_assembly_info_8cs.html", null ],
    [ "KlusterKite.API.Tests.Program.cs", "netcoreapp1_81_2_kluster_kite_8_a_p_i_8_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_kluster_kite_8_a_p_i_2_kluster_kite_8_a_p_i_8_tests_2obj_2_debug_2netcoreapp1_81_2_temporary_gee51a330ba094201cd141dfc26b6f9543.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_kluster_kite_8_a_p_i_2_kluster_kite_8_a_p_i_8_tests_2obj_2_debug_2netcoreapp1_81_2_temporary_ge54992fdfc845cdfdbd996b059678c684.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_kluster_kite_8_a_p_i_2_kluster_kite_8_a_p_i_8_tests_2obj_2_debug_2netcoreapp1_81_2_temporary_ge2558733a93f18c8a54222cf024af5c7a.html", null ]
];