var dir_3eba62059bfa0609867828cbf1419bb0 =
[
    [ "KlusterKite.Data.Tests.AssemblyInfo.cs", "net46_2_kluster_kite_8_data_8_tests_8_assembly_info_8cs.html", null ],
    [ "KlusterKite.Data.Tests.Program.cs", "net46_2_kluster_kite_8_data_8_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_kluster_kite_8_data_2_kluster_kite_8_data_8_tests_2obj_2_debug_2net46_2_temporary_generated_fil7d852b52a514eb2f44ac2caf6dc2eced.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_kluster_kite_8_data_2_kluster_kite_8_data_8_tests_2obj_2_debug_2net46_2_temporary_generated_fil11ce620749b7a2afa285dee1212ea0d6.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_kluster_kite_8_data_2_kluster_kite_8_data_8_tests_2obj_2_debug_2net46_2_temporary_generated_filbd516c679688e0174fbc314b2f586441.html", null ]
];