var dir_545f7151e0898e6cae323e95282282e3 =
[
    [ "KlusterKite.Security.Tests.AssemblyInfo.cs", "netcoreapp1_81_2_kluster_kite_8_security_8_tests_8_assembly_info_8cs.html", null ],
    [ "KlusterKite.Security.Tests.Program.cs", "netcoreapp1_81_2_kluster_kite_8_security_8_tests_8_program_8cs.html", [
      [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ]
    ] ],
    [ "TemporaryGeneratedFile_036C0B5B-1481-4323-8D20-8F5ADCB23D92.cs", "_kluster_kite_8_security_2_kluster_kite_8_security_8_tests_2obj_2_debug_2netcoreapp1_81_2_tempor6f3baadb860b5b215ad70cdaa80966af.html", null ],
    [ "TemporaryGeneratedFile_5937a670-0e60-4077-877b-f7221da3dda1.cs", "_kluster_kite_8_security_2_kluster_kite_8_security_8_tests_2obj_2_debug_2netcoreapp1_81_2_tempor82824a4840e607393bf511cb5322ad4f.html", null ],
    [ "TemporaryGeneratedFile_E7A71F73-0F8D-4B9B-B56E-8E70B10BC5D3.cs", "_kluster_kite_8_security_2_kluster_kite_8_security_8_tests_2obj_2_debug_2netcoreapp1_81_2_temporebe283fdb158cd7f2fbbc6a2ab469b3c.html", null ]
];