// <auto-generated />
using System;
using KlusterKite.NodeManager.ConfigurationSource;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KlusterKite.NodeManager.ConfigurationSource.Migrations
{
    [DbContext(typeof(ConfigurationContext))]
    [Migration("20260409094752_UpdateToEFCore9")]
    partial class UpdateToEFCore9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.CompatibleTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompatibleConfigurationId")
                        .HasColumnType("serial");

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("serial");

                    b.Property<string>("TemplateCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompatibleConfigurationId");

                    b.HasIndex("ConfigurationId");

                    b.ToTable("CompatibleTemplate");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.Configuration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("Finished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsStable")
                        .HasColumnType("boolean");

                    b.Property<int>("MajorVersion")
                        .HasColumnType("integer");

                    b.Property<int>("MinorVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Configurations");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.Migration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("Finished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromConfigurationId")
                        .HasColumnType("serial");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<int>("ToConfigurationId")
                        .HasColumnType("serial");

                    b.HasKey("Id");

                    b.HasIndex("FromConfigurationId");

                    b.HasIndex("ToConfigurationId");

                    b.ToTable("Migrations");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.MigrationLogRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationId")
                        .HasColumnType("serial");

                    b.Property<string>("DestinationPoint")
                        .HasColumnType("text");

                    b.Property<string>("ErrorStackTrace")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("Finished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<int?>("MigrationId")
                        .HasColumnType("serial");

                    b.Property<string>("MigratorName")
                        .HasColumnType("text");

                    b.Property<string>("MigratorTemplateCode")
                        .HasColumnType("text");

                    b.Property<string>("MigratorTemplateName")
                        .HasColumnType("text");

                    b.Property<string>("MigratorTypeName")
                        .HasColumnType("text");

                    b.Property<string>("ResourceCode")
                        .HasColumnType("text");

                    b.Property<string>("ResourceName")
                        .HasColumnType("text");

                    b.Property<string>("SourcePoint")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationId");

                    b.HasIndex("MigrationId");

                    b.ToTable("MigrationLogRecords");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.Role", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AllowedScopeJson")
                        .HasColumnType("text");

                    b.Property<string>("DeniedScopeJson")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.RoleUser", b =>
                {
                    b.Property<Guid>("UserUid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleUid")
                        .HasColumnType("uuid");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("UserUid", "RoleUid");

                    b.HasIndex("RoleUid");

                    b.ToTable("RoleUsers");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.User", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ActiveTill")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("BlockedTill")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.HasKey("Uid");

                    b.HasIndex("Login");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.CompatibleTemplate", b =>
                {
                    b.HasOne("KlusterKite.NodeManager.Client.ORM.Configuration", "CompatibleConfiguration")
                        .WithMany("CompatibleTemplatesForward")
                        .HasForeignKey("CompatibleConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlusterKite.NodeManager.Client.ORM.Configuration", "Configuration")
                        .WithMany("CompatibleTemplatesBackward")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompatibleConfiguration");

                    b.Navigation("Configuration");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.Migration", b =>
                {
                    b.HasOne("KlusterKite.NodeManager.Client.ORM.Configuration", "FromConfiguration")
                        .WithMany()
                        .HasForeignKey("FromConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlusterKite.NodeManager.Client.ORM.Configuration", "ToConfiguration")
                        .WithMany()
                        .HasForeignKey("ToConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromConfiguration");

                    b.Navigation("ToConfiguration");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.MigrationLogRecord", b =>
                {
                    b.HasOne("KlusterKite.NodeManager.Client.ORM.Configuration", "Configuration")
                        .WithMany("MigrationLogs")
                        .HasForeignKey("ConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlusterKite.NodeManager.Client.ORM.Migration", "Migration")
                        .WithMany("Logs")
                        .HasForeignKey("MigrationId");

                    b.Navigation("Configuration");

                    b.Navigation("Migration");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.RoleUser", b =>
                {
                    b.HasOne("KlusterKite.NodeManager.Client.ORM.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KlusterKite.NodeManager.Client.ORM.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.Configuration", b =>
                {
                    b.Navigation("CompatibleTemplatesBackward");

                    b.Navigation("CompatibleTemplatesForward");

                    b.Navigation("MigrationLogs");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.Migration", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("KlusterKite.NodeManager.Client.ORM.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
