//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClusterKit.NodeManager.ConfigurationSource.Migrator.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _201704211334033_Init {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _201704211334033_Init() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClusterKit.NodeManager.ConfigurationSource.Migrator.Migrations.201704211334033_In" +
                            "it", typeof(_201704211334033_Init).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dbo.
        /// </summary>
        internal static string DefaultSchema {
            get {
                return ResourceManager.GetString("DefaultSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H4sIAAAAAAAEAO1d23LcuBF9T1X+YWqekpRXI182ybqk3bIla2uyK8mliytvKoqDGTPmkLMkxysllS/LQz4pvxDwBuLSAAEQ5HC0Kr9YQ6DRaJzGpdHo/t9//nv0w8M6nHxFSRrE0fH05cHhdIIiP14E0ep4us2W3/x1+sP3v//d0YfF+mHyqS73Oi+Ha0bp8fRzlm3ezmap/xmtvfRgHfhJnMbL7MCP1zNvEc9eHR5+N3v5coYwiSmmNZkcXW2jLFij4g/850kc+WiTbb3wPF6gMK1+x1+uC6qTC2+N0o3no+PpSbhNM5T8FGQHF7jwuRd5K5QcYBLLYLVNvAwzeB1vEx9NJ+/CwMMcXqNwOZ14URRnxee3tym6zpI4Wl1v8A9eePO4Qbjc0gtTVPXrbVNct4uHr/IuzpqKNSkfcxyvDQm+fF3JbMZXt5L8lMgUS/UDln72mPe6kOzx9DxYlZL7OV5dIT9OFtMJ3+zbkzDJq8iHIAxQlB1cXp0fiPRe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Target {
            get {
                return ResourceManager.GetString("Target", resourceCulture);
            }
        }
    }
}
